services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports: []
    expose:
      - "3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Tokyo
    command: ["npm", "start"]

  nginx:
    image: nginx:1.25
    container_name: nginx_proxy
    ports:
      - "8800:80"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    environment:
      - TZ=Asia/Tokyo
    networks:
      - app_network
