"""empty message

Revision ID: 30c53071a658
Revises: 
Create Date: 2025-11-12 17:24:53.640055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c53071a658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departments',
    sa.Column('department_id', sa.Integer(), nullable=False, comment='部署ID (PK)'),
    sa.Column('department_extension_number', sa.VARCHAR(length=50), nullable=True, comment='部署の内線'),
    sa.Column('start_date', sa.DATE(), nullable=True, comment='開始日'),
    sa.Column('end_date', sa.DATE(), nullable=True, comment='終了日'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('External_Systems',
    sa.Column('system_id', sa.Integer(), nullable=False, comment='システムID (PK)'),
    sa.Column('system_name', sa.VARCHAR(length=255), nullable=True, comment='外部システム名'),
    sa.Column('start_date', sa.DATE(), nullable=True, comment='開始日'),
    sa.Column('end_date', sa.DATE(), nullable=True, comment='終了日'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('Positions',
    sa.Column('position_id', sa.Integer(), nullable=False, comment='職位ID (PK)'),
    sa.Column('position_name', sa.VARCHAR(length=100), nullable=True, comment='職位名'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False, comment='管理ID (PK)'),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True, comment='氏名'),
    sa.Column('birthday', sa.DATE(), nullable=True, comment='生年月日'),
    sa.Column('hire_date', sa.DATE(), nullable=True, comment='入職日'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Cards',
    sa.Column('card_uid', sa.VARCHAR(length=255), nullable=False, comment='カードUID (PK)'),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=True, comment='管理ID (FK)'),
    sa.Column('card_management_id', sa.VARCHAR(length=255), nullable=True, comment='カード管理用ID'),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True, comment='有効フラグ'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('card_uid')
    )
    op.create_table('D_Numbers',
    sa.Column('d_number_history_id', sa.Integer(), nullable=False, comment='履歴ID (PK)'),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=True, comment='管理ID (FK)'),
    sa.Column('d_number', sa.VARCHAR(length=100), nullable=True, comment='D番号'),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True, comment='有効フラグ'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('d_number_history_id')
    )
    op.create_table('Employee_Number_History',
    sa.Column('employee_number_history_id', sa.Integer(), nullable=False, comment='履歴ID (PK)'),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=True, comment='管理ID (FK)'),
    sa.Column('employee_number', sa.VARCHAR(length=100), nullable=True, comment='職員番号'),
    sa.Column('position_id', sa.Integer(), nullable=True, comment='職位ID (FK)'),
    sa.Column('start_date', sa.DATE(), nullable=True, comment='開始日'),
    sa.Column('end_date', sa.DATE(), nullable=True, comment='終了日'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['Positions.position_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('employee_number_history_id')
    )
    op.create_table('External_System_Exports',
    sa.Column('export_setting_id', sa.Integer(), nullable=False, comment='設定ID (PK)'),
    sa.Column('system_id', sa.Integer(), nullable=True, comment='システムID (FK)'),
    sa.Column('table_name', sa.VARCHAR(length=255), nullable=True, comment='対象テーブル名'),
    sa.Column('column_name', sa.VARCHAR(length=255), nullable=True, comment='対象カラム名'),
    sa.Column('transform_id', sa.VARCHAR(length=255), nullable=True, comment='変換先ID'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['External_Systems.system_id'], ),
    sa.PrimaryKeyConstraint('export_setting_id')
    )
    op.create_table('System_IDs',
    sa.Column('system_id_record_id', sa.Integer(), nullable=False, comment='レコードID (PK)'),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=True, comment='管理ID (FK)'),
    sa.Column('system_id', sa.VARCHAR(length=255), nullable=True, comment='情報システムID'),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True, comment='有効フラグ'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('system_id_record_id')
    )
    op.create_table('User_Departments',
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False, comment='管理ID (PK, FK)'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='部署ID (PK, FK)'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['Departments.department_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'department_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Departments')
    op.drop_table('System_IDs')
    op.drop_table('External_System_Exports')
    op.drop_table('Employee_Number_History')
    op.drop_table('D_Numbers')
    op.drop_table('Cards')
    op.drop_table('Users')
    op.drop_table('Positions')
    op.drop_table('External_Systems')
    op.drop_table('Departments')
    # ### end Alembic commands ###
