"""Add department_name to Departments

Revision ID: 55a2a28e5333
Revises: 30c53071a658
Create Date: 2025-11-12 18:27:25.383406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a2a28e5333'
down_revision = '30c53071a658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_name', sa.VARCHAR(length=255), nullable=True, comment='部署名'))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='開始日')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Departments', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='開始日')
        batch_op.drop_column('department_name')

    # ### end Alembic commands ###
